export const GET_EMAILS = 'GET_EMAILS';
export const DELETE_EMAIL = 'DELETE_EMAIL';
export const SEND_EMAIL = 'SEND_EMAIL';
export const EMAILS_LOADING = 'EMAILS_LOADING';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER';